spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PWD:root}
spring.datasource.url=jdbc:mysql://${DB_IP:localhost}:${DB_PORT:3306}/${DB_NAME:FichaTecnica}?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

site.origin.allowed=${SITE_ALLOW_ORIGIN:http://localhost:4200}

